### ISSUE TITLE
missing TFT_eSPI.h

### ISSUE THREAD

**Issue by roblatour** [alexphredorg/lilygo-weather-esphome#2]
Hi thanks for putting this together.  I gave it a try but got the following error on install:

Compiling /data/lilygo-weather-display/.pioenvs/lilygo-weather-display/src/main.cpp.o
In file included from src/main.cpp:60:
src/tft_espi_display.h:4:10: fatal error: TFT_eSPI.h: No such file or directory

******************************************************************
* Looking for TFT_eSPI.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:TFT_eSPI.h"
* Web  > https://registry.platformio.org/search?q=header:TFT_eSPI.h
*
******************************************************************

 #include <TFT_eSPI.h>
          ^~~~~~~~~~~~
compilation terminated.
Compiling /data/lilygo-weather-display/.pioenvs/lilygo-weather-display/lib8d6/tdisplays3/touchscreen/t_display_s3_touchscreen.cpp.o
In file included from /data/lilygo-weather-display/.piolibdeps/lilygo-weather-display/tdisplays3/touchscreen/t_display_s3_touchscreen.cpp:1:
/data/lilygo-weather-display/.piolibdeps/lilygo-weather-display/tdisplays3/touchscreen/t_display_s3_touchscreen.h:3:10: fatal error: esphome/components/i2c/i2c.h: No such file or directory
 #include "esphome/components/i2c/i2c.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by roblatour** [comment]
I resolved this first error by copying the file TFT_eSPI.h from my Arduino library for the Lilygo TDisplay to the config/.esphome/build/src directoy on my Home Assistant box

I also had to do this with the following files from my Arduino library
User_Setup_Select.h 
i2c.h
Setup24_ST7789.h
but it stopped working after I tried to copy the last file above; got an error v

src/User_Setup_Select.h:52:10: fatal error: User_Setups/Setup24_ST7789.h: No such file or directory
 #include <User_Setups/Setup24_ST7789.h>            // Setup file for DSTIKE/ESP32/ESP8266 configured for ST7789 240 x 240

**Comment by alexphredorg** [comment]
TFT_eSPI.h should be pulled in through the dependency graph.  Below is what the build shows for me.

Did you change any of the includes or libraries at the top of the yaml file?

LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
Dependency Graph
|-- AsyncTCP-esphome @ 1.2.2
|-- SPI @ 2.0.0
|-- FS @ 2.0.0
|-- SPIFFS @ 2.0.0
|-- TFT_eSPI @ 2.4.71+sha.9129d5a
|-- OpenFontRender @ 1.0.0+sha.b4cc8f7
|-- WiFi @ 2.0.0
|-- Update @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 2.1.0
|   |-- AsyncTCP-esphome @ 1.2.2
|-- DNSServer @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- noise-c @ 0.1.4
|   |-- libsodium @ 1.10018.1
|-- ArduinoJson @ 6.18.5

**Comment by roblatour** [comment]
II did not change any of the included files at the top of the yaml file.

Here is what I am seeing for my dependency graph:

Dependency Graph
|-- AsyncTCP-esphome @ 1.2.2
|-- SPI @ 2.0.0
|-- FS @ 2.0.0
|-- SPIFFS @ 2.0.0
|-- tdisplays3 @ 0.0.0+20230509122516.sha.e89bdb0
|-- OpenFontRender @ 1.0.1+sha.96a29bc
|-- WiFi @ 2.0.0
|-- Update @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 2.1.0
|   |-- AsyncTCP-esphome @ 1.2.2
|-- DNSServer @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- noise-c @ 0.1.4
|   |-- libsodium @ 1.10018.1
|-- ArduinoJson @ 6.18.5

![sss](https://github.com/alexphredorg/lilygo-weather-esphome/assets/5200730/c9c71d2e-30ed-4915-8ebd-d9c824dbfd73)

**Comment by alexphredorg** [comment]
I did a clean build and ended up in the same place as you, some of the dependencies might have changed over the last couple of months.  I'll update you when I have a chance to dig in.

**Comment by roblatour** [comment]
Thanks - just trying to keep my wife happy by building one of these :-)

**Comment by alexphredorg** [comment]
The library that I was using to control the display changed to a different API.  I will upload a fixed version in a day or two (probably without hourly forecast working at first).

**Comment by alexphredorg** [comment]
I pushed the fix for this.

**Comment by roblatour** [comment]
Thanks for providing this update.  It works great!
